FROM golang:1.23 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY pub ./pub
COPY sub ./sub
COPY pkg ./pkg

FROM build-stage AS run-test-stage

RUN go test -v --skip "_IT" ./...

CMD ["go", "test", "-v", "./..."]
